export * from "./FullTest/FullTest";
export * from "./Login/Login";
export * from "./Registration/Registration";
export * from "./Tests/Tests";
export * from "./UserInfo/UserInfo";
export * from "./AddTest/AddTest";
export * from "./About/About";
export * from "./Tariffs/Tariffs";
export * from "./Programs/Programs";
